

package userinterface.AdministrativeRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.LoginJPanel;

/**
 *
 * @author piyush.dandekar
 */
@SuppressWarnings("unchecked")
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    private EcoSystem business;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise,EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        evalue.setText(enterprise.getName());
        this.business=business;
    }
    @SuppressWarnings("unchecked")
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userbtn = new javax.swing.JButton();
        empbtn = new javax.swing.JButton();
        orgbtn = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        evalue = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logoutbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setBorder(new javax.swing.border.MatteBorder(null));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userbtn.setBackground(new java.awt.Color(255, 153, 153));
        userbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userbtn.setText("USER DETAILS");
        userbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userbtnActionPerformed(evt);
            }
        });
        add(userbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 190, 130));

        empbtn.setBackground(new java.awt.Color(255, 153, 102));
        empbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        empbtn.setText("EMPLOYEE");
        empbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empbtnActionPerformed(evt);
            }
        });
        add(empbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 190, 130));

        orgbtn.setBackground(new java.awt.Color(255, 102, 102));
        orgbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        orgbtn.setText("ORGANIZATION");
        orgbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgbtnActionPerformed(evt);
            }
        });
        add(orgbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 210, 130));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("ENTERPRISE : ");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 170, 30));

        evalue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(evalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 200, 30));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("ADMINISTRATION MANAGEMENT");
        jPanel1.add(jLabel1);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 50));

        logoutbtn.setBackground(new java.awt.Color(255, 0, 0));
        logoutbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logoutbtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutbtn.setText("Logout");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 110, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void userbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userbtnActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel manageuser = new ManageUserAccountJPanel(userProcessContainer, enterprise,business);
        userProcessContainer.add("ManageUserAccountJPanel", manageuser);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_userbtnActionPerformed

    private void empbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empbtnActionPerformed

        ManageEmployeeJPanel manageEmp = new ManageEmployeeJPanel(userProcessContainer, enterprise.getOrganizationDirectory(),business);
        userProcessContainer.add("manageEmployeeJPanel", manageEmp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_empbtnActionPerformed

    private void orgbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgbtnActionPerformed

        ManageOrganizationJPanel manageOrg = new ManageOrganizationJPanel(userProcessContainer, enterprise.getOrganizationDirectory(),enterprise,business);
        userProcessContainer.add("manageOrganizationJPanel", manageOrg);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_orgbtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        LoginJPanel loginPanel=new LoginJPanel();
        userProcessContainer.add("loginPanel",loginPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        dB4OUtil.storeSystem(business);
    }//GEN-LAST:event_logoutbtnActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton empbtn;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel evalue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton orgbtn;
    private javax.swing.JButton userbtn;
    // End of variables declaration//GEN-END:variables
    
}
