/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import Business.Organization.OrganizationDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.Enterprise.HospitalEnterprise;
import Business.Enterprise.HelpCareCenterEnterprise;
import Business.Enterprise.Homeless;
import userinterface.LoginJPanel;

/**
 *
 * @author piyush.dandekar
 */
@SuppressWarnings("unchecked")
public class ManageOrganizationJPanel extends javax.swing.JPanel {

    private OrganizationDirectory directory;
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private EcoSystem business;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageOrganizationJPanel(JPanel userProcessContainer,OrganizationDirectory directory, Enterprise enterprise,EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.directory = directory;
        this.business=business;
        this.enterprise = enterprise;
        populateTable();
        populateCombobox();
    }
    
    private void populateCombobox(){
        orgComboBox.removeAllItems();
        for (Type type : Organization.Type.values()){

            if (enterprise.getEnterpriseType().getValue().equals(Enterprise.EnterpriseType.Hospital.toString())) {
                if (type.getValue().equals(Organization.Type.Doctor.getValue()) || type.getValue().equals(Organization.Type.Lab.getValue()) || type.getValue().equals(Organization.Type.MedicalCampOrganizer.getValue())) {
                    orgComboBox.addItem(type);
                }
            }
            
            if (enterprise.getEnterpriseType().getValue().equals(Enterprise.EnterpriseType.HelpCareCenter.toString())) {
                if (type.getValue().equals(Organization.Type.Volunteer.getValue()) || type.getValue().equals(Organization.Type.FundsProvider.getValue())) {
                    orgComboBox.addItem(type);
                }
            }
            
            if (enterprise.getEnterpriseType().getValue().equals(Enterprise.EnterpriseType.Homeless.toString())) {
                if (type.getValue().equals(Organization.Type.RefugeeCamp.getValue()) || type.getValue().equals(Organization.Type.Amenities.getValue()) || type.getValue().equals(Organization.Type.Inventory.getValue())){
                    orgComboBox.addItem(type);
                }
            }
        }
    }

    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) orgtable.getModel();
        
        model.setRowCount(0);
        
        for (Organization organization : directory.getOrganizationArrayList()){
            Object[] row = new Object[2];
            row[0] = organization.getOrganizationID();
            row[1] = organization.getName();
            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        orgtable = new javax.swing.JTable();
        addorg = new javax.swing.JButton();
        orgComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        backbtnn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(null);

        orgtable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        orgtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orgtable);

        add(jScrollPane1);
        jScrollPane1.setBounds(50, 267, 740, 166);

        addorg.setBackground(new java.awt.Color(102, 102, 102));
        addorg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addorg.setText("Add Organization");
        addorg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addorgActionPerformed(evt);
            }
        });
        add(addorg);
        addorg.setBounds(370, 190, 249, 31);

        orgComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        orgComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(orgComboBox);
        orgComboBox.setBounds(367, 131, 313, 28);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Select Organization : ");
        add(jLabel1);
        jLabel1.setBounds(167, 131, 190, 28);

        backbtnn.setBackground(new java.awt.Color(102, 102, 102));
        backbtnn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backbtnn.setText("<< Back");
        backbtnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnnActionPerformed(evt);
            }
        });
        add(backbtnn);
        backbtnn.setBounds(46, 18, 130, 31);

        logoutbtn.setBackground(new java.awt.Color(255, 0, 0));
        logoutbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logoutbtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutbtn.setText("Logout");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        add(logoutbtn);
        logoutbtn.setBounds(758, 18, 87, 31);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ORGANIZATION");
        add(jLabel2);
        jLabel2.setBounds(320, 20, 240, 29);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        add(jPanel1);
        jPanel1.setBounds(0, 0, 890, 80);
    }// </editor-fold>//GEN-END:initComponents

    private void addorgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addorgActionPerformed

        if(enterprise instanceof HospitalEnterprise){
            if (directory.getOrganizationArrayList().size() == 3)
            removeItems();
            else
            addItemsInDirectory();
        }
        if(enterprise instanceof HelpCareCenterEnterprise){
            if (directory.getOrganizationArrayList().size() == 2)
            removeItems();
            else
            addItemsInDirectory();
        }
        if(enterprise instanceof Homeless){
            if (directory.getOrganizationArrayList().size() == 3)
            removeItems();
            else
            addItemsInDirectory();
        }
        dB4OUtil.storeSystem(business);
    }//GEN-LAST:event_addorgActionPerformed

    private void backbtnnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnnActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backbtnnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        LoginJPanel loginJPanel=new LoginJPanel();
        userProcessContainer.add("loginJPanel",loginJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        dB4OUtil.storeSystem(business);
    }//GEN-LAST:event_logoutbtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addorg;
    private javax.swing.JButton backbtnn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JComboBox orgComboBox;
    private javax.swing.JTable orgtable;
    // End of variables declaration//GEN-END:variables
    
    private void removeItems() {
        orgComboBox.removeAll();
        orgComboBox.setEnabled(false);
        JOptionPane.showMessageDialog(null, "You cannot add the same organization again. All organizations are created already.");
    }

    private void addItemsInDirectory() {
        Organization.Type type = (Organization.Type) orgComboBox.getSelectedItem();
        directory.createOrganization(type);
        populateTable();
        orgComboBox.removeItem(orgComboBox.getSelectedItem());
        JOptionPane.showMessageDialog(null, "Organization added successfully.");
    }
}
