/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.MedicalCampOrganizerRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HousesMedicalCampRequest;
import Business.WorkQueue.MedicalCamp;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author piyush.dandekar
 */
@SuppressWarnings("unchecked")
public class RequestCampsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestCampsJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private HousesMedicalCampRequest Hmcrequest;
    private EcoSystem business;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public RequestCampsJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, HousesMedicalCampRequest hmcworkReq,EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.Hmcrequest = hmcworkReq;
        this.business=business;
        valueLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        messageJTextField = new javax.swing.JTextField();
        requestDoctorJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(null);

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel);
        enterpriseLabel.setBounds(171, 148, 120, 30);

        valueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(valueLabel);
        valueLabel.setBounds(324, 148, 503, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Message");
        add(jLabel1);
        jLabel1.setBounds(171, 207, 135, 26);
        add(messageJTextField);
        messageJTextField.setBounds(324, 207, 503, 33);

        requestDoctorJButton.setBackground(new java.awt.Color(102, 102, 102));
        requestDoctorJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        requestDoctorJButton.setText("Send ");
        requestDoctorJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestDoctorJButtonActionPerformed(evt);
            }
        });
        add(requestDoctorJButton);
        requestDoctorJButton.setBounds(350, 290, 177, 31);

        backJButton.setBackground(new java.awt.Color(102, 102, 102));
        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(31, 10, 130, 31);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Camp Message Request");
        add(jLabel2);
        jLabel2.setBounds(270, 70, 384, 31);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/MedicalCampOrganizerRole/medicalcamp organizer (1).jpg"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(0, 60, 890, 580);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 80);
    }// </editor-fold>//GEN-END:initComponents

    private void requestDoctorJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestDoctorJButtonActionPerformed
        // TODO add your handling code here:
        String message = messageJTextField.getText();

        if(Hmcrequest.getStatus().equals("Pending")){
            Hmcrequest.setStatus("Requested Doctor");
            MedicalCamp request = new MedicalCamp();
            request.setMessage(message);
            System.out.println("user ac of mcr"+userAccount);
            request.setSender(userAccount);
            request.setStatus("Sent");
            request.setHmcwr(Hmcrequest);

            Organization org = null;
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationArrayList()){
                if (organization instanceof DoctorOrganization){
                    org = organization;
                    break;
                }
            }
            if (org!=null){
                org.getWorkQueue().getWorkRequestList().add(request);
                userAccount.getWorkQueue().getWorkRequestList().add(request);
            }
            dB4OUtil.storeSystem(business);
        }
        else{
            JOptionPane.showMessageDialog(null, "Already Raised Request");
            return;
        }
        messageJTextField.setText("");
        
           JOptionPane.showMessageDialog(null, "Done");   
    }//GEN-LAST:event_requestDoctorJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        MedicalCampOrganizerWorkAreaJPanel mwjp = (MedicalCampOrganizerWorkAreaJPanel) component;
        mwjp.populateTable();
        mwjp.populateTableReqFromVol();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField messageJTextField;
    private javax.swing.JButton requestDoctorJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
